### ISSUE TITLE
Add thumbnail images and full size images

### ISSUE THREAD

**Issue by ravishakya** [taras-d/images-grid#14]
Currently thumbnail images and lightbox images are same. This will increase the page load time. Can u add another parameter for thumbnail images

eg.

```
$('#imgs').imagesGrid({
    images: ['img1.png','img2.png','img3.png'],
    thumbnail: ['thumb_img1.png','thumb_img2.png','thumb_img3.png'],
  }); ```

**Comment by taras-d** [comment]
`thumbnail` property - https://github.com/taras-d/images-grid#images-array

**Comment by vimalsaifudin** [comment]
Is it possible to attach video files along with images ?
