### ISSUE TITLE
Issue if i select my wrap-item class (include the images-grid class inside a list with items)

### ISSUE THREAD

**Issue by spanakorizo** [taras-d/images-grid#21]
Hello and thanks for your plugin! 

However i am having an issue as i am trying to include it with a list of items, for example products.
If i select for example the default #gallery1 id the grid-images will only show at the first item and will not continue in the rest.

Then i thought to select my list item class for example .wrap-item to attach to every item.
Then the plugin will render in all the items but will remove all my content there, only the images will stay in every item.

For example code:

<li class="wrap-item">
<div class="container">
<div class="name"> Product name </div>
<div class= "price">120$</div>
..
...
</div>

I think the correct approach would be to include a <div id="gallery1"></div> id inside my .wrap-item but as i said only the 1st item will include the grid-images (including all my other elements as well) but the rest of the items would only render my elements without the images-grid.

Any ideas maybe how to modify the images-grid.js or any other method maybe before or after loading items to the DOM?

EDIT: Actually it's very simple issue and doesn't have to do with my listing, even in your sample files if you add multiple elements with the same ID then the images-grid will render only in the 1st.

**Comment by spanakorizo** [comment]
Here is an example of what i mean (this is if i choose to include the grid element inside my items container)

![example](https://user-images.githubusercontent.com/3715496/146800595-93a5a546-36b3-4fd2-832d-7fa935fb2340.jpg)

**Comment by taras-d** [comment]
Hello.
In order to create multiple images grids, each element should have own id. For example:

```
<div id="gallery1"></div>

<div id="gallery2"></div>

<div id="gallery3"></div>

<script>
  $('#gallery1').imagesGrid({ .... });
  
  $('#gallery2').imagesGrid({ .... });
  
  $('#gallery3').imagesGrid({ .... });
</script>
```

**Comment by spanakorizo** [comment]
Thanks for your reply , love your plugin and i was wondering if would be any tricky way to make it work with the same id.
I have tested and i can confirm that it's possible to add as many image-grids you want if they only have different id.
As you understand won't be possible to add different ids as the items are coming through Loop, this id will have to be unique so in every product will be the same ids.

Any thoughts?

Thanks again!

**Comment by taras-d** [comment]
You can use class instead of id:
```
<div class="gallery"></div>
<div class="gallery"></div>
<div class="gallery"></div>

<script>
  $('.gallery').imagesGrid({ .... });
</script>
```

**Comment by taras-d** [comment]
Using multiple elements with same "id" is not recommended and jQuery selects only first element.

https://stackoverflow.com/questions/8498579/how-does-jquery-work-when-there-are-multiple-elements-with-the-same-id-value

**Comment by taras-d** [comment]
Just noticed, there is a trick in jQuery to select multiple elements with same id - `$('body #gallery')`

**Comment by spanakorizo** [comment]
Wow looks like it will do the trick! Now i will have to see if can locate the images for each item from product's gallery!
