### ISSUE TITLE
Caption to images

### ISSUE THREAD

**Issue by rajkhowa** [taras-d/images-grid#4]
This is a very beautiful plug-in and the documentation is easy to understand.
I have an issue. After clicking, when the images are displayed in enlarged form, I need to put a caption above the image boundary. Can it be done?

**Comment by taras-d** [comment]
@rajkhowa thanks!

Look at the `images` option - property **caption**.
https://github.com/taras-d/images-grid#images-array

**Comment by rajkhowa** [comment]
That worked like a charm!
Thank you very much and again excellent work!
