### ISSUE TITLE
This does not work with Wordpress

### ISSUE THREAD

**Issue by chamilapj** [taras-d/images-grid#5]
I tried to add this gallery to my wordpress site.

But it does not work.

can you please help me to solve this.

Thank you,
Chamila

**Comment by taras-d** [comment]
Hi @chamilapj 
I never worked with Wordpress. 
But I will try to help you.<br>
1. Do you try to add plugin like on this page https://taras-d.github.io/images-grid/ ?
2. What exactly don't work? (Is there some errors in browser console?)

**Comment by chamilapj** [comment]
1: yes i used the plugin. all works. when i dynamically try to add images to array as below

<script>
            $('#imgGrid1').imagesGrid({
                images: [
                    '<?php echo get_template_directory_uri() ?>/imgs/1.jpg',
                    '<?php echo get_template_directory_uri() ?>/mgs/2.jpg',
                    '<?php echo get_template_directory_uri() ?>/imgs/3.jpg',
                    '<?php echo get_template_directory_uri() ?>/imgs/4.jpg',
                    '<?php echo get_template_directory_uri() ?>/imgs/5.jpg',
                    '<?php echo get_template_directory_uri() ?>/imgs/6.jpg'
                ]
            });         
        </script>
Result comes like this
<script>
            $('#imgGrid1').imagesGrid({
                images: [
                    'http://localhost/dg/wp-content/themes/ed/imgs/1.jpg',
                    'http://localhost/dg/wp-content/themes/ed/mgs/2.jpg',
                    'http://localhost/dg/wp-content/themes/ed/imgs/3.jpg',
                    'http://localhost/dg/wp-content/themes/ed/imgs/4.jpg',
                    'http://localhost/dg/wp-content/themes/ed/imgs/5.jpg',
                    'http://localhost/dg/wp-content/themes/ed/imgs/6.jpg'
                ]
            });
</script>
            

i think above everthing is okay

but some error in console
Uncaught TypeError: $(...).imagesGrid is not a function

**Comment by taras-d** [comment]
Try to use `jQuery` instead of `$`

``` javascript
jQuery('#imgs').imagesGrid(...);
```

http://stackoverflow.com/questions/12343714/typeerror-is-not-a-function-when-calling-jquery-function

**Comment by chamilapj** [comment]
Uncaught TypeError: jQuery(...).imagesGrid is not a function

still errror comes

**Comment by taras-d** [comment]
This is not a plugin error.
This error related to Wordpress jquery in your page.

You need to make sure:
1. jquery included in your page and work correctly
2. jquery script should be added before any other jquery plugins
3. jquery has no conflicts with other libraries

**Comment by chamilapj** [comment]
yes works and included before all jquery plugins

**Comment by chamilapj** [comment]
other jquery plugins are working well

**Comment by taras-d** [comment]
Which version of Wordpress you use?

**Comment by chamilapj** [comment]
I am using wordpress 4.6 

using Wamp server as the local server

I am using owl carousel and it is working well.

error is $(...).imagesGrid is not a function

I tried twice with wordpress same error comes.

can you please check using with wordpress

**Comment by taras-d** [comment]
Tested on WP 4.6

**1.** 
Add plugin files to the theme folder. In my case theme `twentysixteen`.
![plugin-files](https://cloud.githubusercontent.com/assets/5041444/18229677/d739d5c0-728a-11e6-8fd2-b78eb7b0ba74.png)

**2.** 
Use WP special function to load plugin scripts. 
Add this code to the file `functions.php` in theme folder.

``` php
function images_grid_scripts() {
        wp_enqueue_script(
                'images-grid-script',
                get_template_directory_uri() . '/jq-plugins/images-grid/images-grid.js',
                array('jquery')
        );
        wp_enqueue_style(
                'images-grid-style',
                get_template_directory_uri() . '/jq-plugins/images-grid/images-grid.css'
        );
}
add_action('wp_enqueue_scripts', 'images_grid_scripts');
```

**3.**
Now you can use plugin. For example in the post content.
![post-content](https://cloud.githubusercontent.com/assets/5041444/18229723/f2694168-728b-11e6-989f-b95c42a9946e.png)

**Result**:
![result](https://cloud.githubusercontent.com/assets/5041444/18229736/6162ce5e-728c-11e6-8580-3df9553ce9e2.png)

Also check this link https://premium.wpmudev.org/blog/adding-jquery-scripts-wordpress/

**Comment by chamilapj** [comment]
Thank you very much! 
it is working in this way.
