### ISSUE TITLE
how properly use the array of images with title, alt and caps?

### ISSUE THREAD

**Issue by chidalgom1503** [taras-d/images-grid#6]
Hi, 
I was testing this great plugin ,but I cant make alt, titles or cap appers. I read the documentation and use the same code in the info for this example but nothing happens, not even display the images... what Im doing wrong?

Thanks!

By the way, Im using something like this:

images: [
{src: 'images/image01.jpg', alt: 'Car',title: 'Car',caption: 'Supercar'},
{src: 'images/image02.jpg', alt: 'Bike',title: 'Bike',caption: 'Superbike'},
]

and like this:

images: [
'images/image01.jpg',{
      src: 'image01.jpg',    
      alt: 'Car',          
      title: 'Car',        
      caption: 'Supercar'  
    },
'images/image02.jpg',{
      src: 'image02.jpg',    
      alt: 'Bike',         
      title: 'Bike',        
      caption: 'Superbike'  
    },
]

Is there other way to add this info for every image? its important to display the info on all the images in gallery.

**Comment by taras-d** [comment]
Hi @chidalgom1503 

There is two ways to specify image in images array
```javascript
$('#my-gallery').imagesGrid({
    images: [
        // 1. By string
        'path/to/image-1',
        // 2. By object ('src' property is required)
        {
            src: 'path/to/image-2',
            alt: 'Image 2',
            title: 'Image 2',
            caption: 'Second Image'
        }
    ],
    align: true
});
```

Please look at the [Code from the demo page](https://github.com/taras-d/images-grid/blob/master/index.html#L36-L47)
(Only 4th image has caption, which appear above image)

**Comment by chidalgom1503** [comment]
thanks, i was messing around and finally get it.

many thanks!
