### ISSUE TITLE
Issue in modal

### ISSUE THREAD

**Issue by iwoanton** [taras-d/images-grid#8]
Hi,
I use this plugin in a modal, in this template https://blackrockdigital.github.io/startbootstrap-freelancer/ when open a  portofolio modal, the gallery loads in the html and the images, all good the problem is with the height in the image-wrap div which is set to 0px

< div class="image-wrap" **style="height: 0px;"**>< img src="img_url" alt="" title=""></div>

How can i do

Thanks

**Comment by iwoanton** [comment]
Resolved comenting this line in js

imgWrap.height(itemHeight);

Thanks

**Comment by taras-d** [comment]
You also can set `align` option to `false` - to skip setting image height.
https://github.com/taras-d/images-grid#align-boolean
