### ISSUE TITLE
Option to force the "View All" link to appear

### ISSUE THREAD

**Issue by shefik** [taras-d/images-grid#9]
Please add an option to force the "View All" link to always appear, in order to open the modal.

I have a use case where I have one image, and when you open the modal, the image is visible full-size.

**Comment by taras-d** [comment]
Hi @shefik 

Added [Show view all option](https://github.com/taras-d/images-grid/blob/master/README.md#showviewall-stringboolean)

**Comment by shefik** [comment]
Thanks!
